# spring 项目配置
spring:
  application:
    name: geo-blog-backend
  security:
    filter:
      order: -100
    user:
      name: user
      password: 123456
    jwt:
      key: dihaozhe
      expire: 24
  datasource:
    url: jdbc:mysql://localhost:3306/db_geo_blog?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  mail:
    host: smtp.163.com
    username: dihaozhe365@163.com
    password: KVVCXKVWIRWXKYGG
  rabbitmq:
      addresses: localhost
      username: admin
      password: admin
      virtual-host: /
#SQL 日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
# GeoBlog 配置
geo-blog:
  version: 1.0.0

# 后端服务器端口号配置 8090
server:
  port: 8090

# 文件保存路径默认在服务器的下载文件夹中,在部署时需要按照下列路径创建好对应的文件夹
img:
  root: '/Users/dihaozhe/Downloads/img'

# slf4j 日志配置
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %-5level [%thread] %logger{15} ===> %msg%n"

# knife4j 接口文档访问 http://localhost:8090/doc.html
knife4j:
  enable: true
  basic:
    enable: true
    # Basic认证用户名
    username: root
    # Basic认证密码
    password: 123456
  setting:
    language: zh_cn
    enable-footer: false
    enable-footer-custom: true
    footer-custom-content: MIT License Copyright (c) 2024 邸浩哲

# springdoc-openapi 接口文档配置
springdoc:
  swagger-ui:
    path: /swagger.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    group: 'default'
    paths-to-match: '/**'
    packages-to-scan: com.dihaozhe.geoblogbackend.controller